// Code generated by "stringer -type=ServerType"; DO NOT EDIT.

package handshake

import "strconv"

const _ServerType_name = "LoadBalancingServerDataServer"

var _ServerType_index = [...]uint8{0, 19, 29}

func (i ServerType) String() string {
	if i < 0 || i >= ServerType(len(_ServerType_index)-1) {
		return "ServerType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ServerType_name[_ServerType_index[i]:_ServerType_index[i+1]]
}
