// Code generated by "stringer -type Enum consts.go"; DO NOT EDIT.

package rmeta

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Base-0]
	_ = x[Char-1]
	_ = x[Short-2]
	_ = x[Int-3]
	_ = x[Long-4]
	_ = x[Float-5]
	_ = x[Counter-6]
	_ = x[CharStar-7]
	_ = x[Double-8]
	_ = x[Double32-9]
	_ = x[LegacyChar-10]
	_ = x[UChar-11]
	_ = x[UShort-12]
	_ = x[UInt-13]
	_ = x[ULong-14]
	_ = x[Bits-15]
	_ = x[Long64-16]
	_ = x[ULong64-17]
	_ = x[Bool-18]
	_ = x[Float16-19]
	_ = x[OffsetL-20]
	_ = x[OffsetP-40]
	_ = x[Object-61]
	_ = x[Any-62]
	_ = x[Objectp-63]
	_ = x[ObjectP-64]
	_ = x[TString-65]
	_ = x[TObject-66]
	_ = x[TNamed-67]
	_ = x[Anyp-68]
	_ = x[AnyP-69]
	_ = x[AnyPnoVT-70]
	_ = x[STLp-71]
	_ = x[Skip-100]
	_ = x[SkipL-120]
	_ = x[SkipP-140]
	_ = x[Conv-200]
	_ = x[ConvL-220]
	_ = x[ConvP-240]
	_ = x[STL-300]
	_ = x[STLstring-365]
	_ = x[Streamer-500]
	_ = x[StreamLoop-501]
	_ = x[Cache-600]
	_ = x[Artificial-1000]
	_ = x[CacheNew-1001]
	_ = x[CacheDelete-1002]
	_ = x[NeedObjectForVirtualBaseClass-99997]
	_ = x[Missing-99999]
	_ = x[Int8-1]
	_ = x[Int16-2]
	_ = x[Int32-3]
	_ = x[Int64-4]
	_ = x[Uint8-11]
	_ = x[Uint16-12]
	_ = x[Uint32-13]
	_ = x[Uint64-14]
	_ = x[Float32-5]
	_ = x[Float64-8]
}

const _Enum_name = "BaseCharShortIntLongFloatCounterCharStarDoubleDouble32LegacyCharUCharUShortUIntULongBitsLong64ULong64BoolFloat16OffsetLOffsetPObjectAnyObjectpObjectPTStringTObjectTNamedAnypAnyPAnyPnoVTSTLpSkipSkipLSkipPConvConvLConvPSTLSTLstringStreamerStreamLoopCacheArtificialCacheNewCacheDeleteNeedObjectForVirtualBaseClassMissing"

var _Enum_map = map[Enum]string{
	0:     _Enum_name[0:4],
	1:     _Enum_name[4:8],
	2:     _Enum_name[8:13],
	3:     _Enum_name[13:16],
	4:     _Enum_name[16:20],
	5:     _Enum_name[20:25],
	6:     _Enum_name[25:32],
	7:     _Enum_name[32:40],
	8:     _Enum_name[40:46],
	9:     _Enum_name[46:54],
	10:    _Enum_name[54:64],
	11:    _Enum_name[64:69],
	12:    _Enum_name[69:75],
	13:    _Enum_name[75:79],
	14:    _Enum_name[79:84],
	15:    _Enum_name[84:88],
	16:    _Enum_name[88:94],
	17:    _Enum_name[94:101],
	18:    _Enum_name[101:105],
	19:    _Enum_name[105:112],
	20:    _Enum_name[112:119],
	40:    _Enum_name[119:126],
	61:    _Enum_name[126:132],
	62:    _Enum_name[132:135],
	63:    _Enum_name[135:142],
	64:    _Enum_name[142:149],
	65:    _Enum_name[149:156],
	66:    _Enum_name[156:163],
	67:    _Enum_name[163:169],
	68:    _Enum_name[169:173],
	69:    _Enum_name[173:177],
	70:    _Enum_name[177:185],
	71:    _Enum_name[185:189],
	100:   _Enum_name[189:193],
	120:   _Enum_name[193:198],
	140:   _Enum_name[198:203],
	200:   _Enum_name[203:207],
	220:   _Enum_name[207:212],
	240:   _Enum_name[212:217],
	300:   _Enum_name[217:220],
	365:   _Enum_name[220:229],
	500:   _Enum_name[229:237],
	501:   _Enum_name[237:247],
	600:   _Enum_name[247:252],
	1000:  _Enum_name[252:262],
	1001:  _Enum_name[262:270],
	1002:  _Enum_name[270:281],
	99997: _Enum_name[281:310],
	99999: _Enum_name[310:317],
}

func (i Enum) String() string {
	if str, ok := _Enum_map[i]; ok {
		return str
	}
	return "Enum(" + strconv.FormatInt(int64(i), 10) + ")"
}
