// DO NOT EDIT; automatically generated by brio-gen

package image

import (
	"encoding/binary"
)

// MarshalBinary implements encoding.BinaryMarshaler
func (o *Point) MarshalBinary() (data []byte, err error) {
	var buf [8]byte
	binary.LittleEndian.PutUint64(buf[:8], uint64(o.X))
	data = append(data, buf[:8]...)
	binary.LittleEndian.PutUint64(buf[:8], uint64(o.Y))
	data = append(data, buf[:8]...)
	return data, err
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler
func (o *Point) UnmarshalBinary(data []byte) (err error) {
	o.X = int(binary.LittleEndian.Uint64(data[:8]))
	data = data[8:]
	o.Y = int(binary.LittleEndian.Uint64(data[:8]))
	data = data[8:]
	_ = data
	return err
}
