// Code generated by "stringer -type Kind"; DO NOT EDIT.

package rcompress

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Inherit - -1]
	_ = x[UseGlobal-0]
	_ = x[ZLIB-1]
	_ = x[LZMA-2]
	_ = x[OldCompression-3]
	_ = x[LZ4-4]
	_ = x[ZSTD-5]
	_ = x[UndefinedCompression-6]
}

const _Kind_name = "InheritUseGlobalZLIBLZMAOldCompressionLZ4ZSTDUndefinedCompression"

var _Kind_index = [...]uint8{0, 7, 16, 20, 24, 38, 41, 45, 65}

func (i Kind) String() string {
	i -= -1
	if i < 0 || i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
